environment:
  nodejs_version: "18"

branches:
  only:
    - master
    - main

cache: node_modules

install:
  - yarn install

build: off

build_script:
  - yarn run build

test_script:
  - yarn run lint && yarn test
