environment:
  nodejs_version: "18"

branches:
  only:
    - master
    - main

cache:
  - node_modules -> yarn.lock

install:
  - yarn install --frozen-lockfile

build_script:
  - yarn run build || exit 1
  - if not exist dist\bundle.js exit 1

test_script:
  - yarn run lint || exit 1
  - yarn test || exit 1

on_finish:
  - ps: if($env:APPVEYOR_JOB_RESULT -eq "failed") { exit 1 }